server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  datasource:
    password:
    url: jdbc:postgresql://localhost:5433/registration
    username:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:

